[tool.poetry.dependencies]
python = ">=3.9,<4.0"

[tool.poetry]
package-mode = false

[tool.poetry.group.tensorflow.dependencies]
h5py = ">=2.10.0,<=3.13.0"
tensorflow = ">=2.4.0,<=2.16.0"
tensorflow-addons = { version = "<=0.23.0", markers = "python_version <= '3.10'" }