[tool.poetry.dependencies]
python = ">=3.9,<4.0"

[tool.poetry]
package-mode = false

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.group.dev.dependencies]
torch = { version = ">=1.8.0,<=2.7.1", source = "pytorch-cpu" }
torchvision = { version = "<=0.22.0", source = "pytorch-cpu" }

[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
torchaudio = { version = "<=2.6.0", source = "pytorch-cpu" }
transformers = "<=4.47.1"
huggingface-hub = "<=0.25.2"