[tool.poetry.dependencies]
python = ">=3.9,<4.0"

[tool.poetry]
package-mode = false

[tool.poetry.group.onnx.dependencies]
protobuf = ">=3.20.0,<=4.25.0"
docopt = "<=0.6.2"
onnx = ">=1.8.0,<=1.18.0"
onnxruntime = [
    { version = ">=1.8.0,<=1.19.2", markers = "python_version <= '3.9'" },
    { version = ">=1.8.0", markers = "python_version >= '3.10'" }
]
