name: OVC
on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target branch for the build; taken from event context by default'
        type: string
        required: false
  merge_group:
  push:
    branches:
      - 'master'
      - 'releases/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Pylint-UT:
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Configure poetry
        uses: ./.github/actions/install_poetry
        
      - name: Install Test dependencies
        run: poetry install --with linters

      - name: Pylint-OVC
        run: poetry run pylint -d C,R,W openvino/tools/ovc
        working-directory: tools/ovc

  Overall_Status:
    name: ci/gha_overall_status_ovc
    needs: [Pylint-UT]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check status of all jobs
        if: >-
          ${{
            contains(needs.*.result, 'failure') ||
            contains(needs.*.result, 'cancelled')
          }}
        run: exit 1
